# -*- coding: utf-8 -*-
"""DIS18_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145YmEvL69PGFUxIqbDIqkeOrDMbX1Jzr
"""

# Commented out IPython magic to ensure Python compatibility.
# Java (für PyTerrier)
!apt-get install -y openjdk-11-jdk

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

# Python libs
!pip install pyterrier lightgbm pandas numpy sentence-transformers

# Repo klonen
!git clone https://github.com/Vico0306/longeval-sci.git
# %cd longeval-sci

!pip install ir_datasets

!pip install ir_datasets ir_datasets_longeval

from ir_datasets_longeval import load # jetzt für Snapshot 2 und 3 vorher wurde hier Snapshot 1 geladen

dataset = load("longeval-sci-2026/snapshot-2")
# train datensatz enthält querries dafür /train/dctr oder /raw
# citatzations ber drive ist besser
# /train/dctr oder /raw für die querries

import ir_datasets
print([d for d in ir_datasets.registry if "longeval" in d])

# Make split bei t1 von 2026 70/30 für validierung nutzen wir die 30%
# um mehr datensätze zu bekommen können wir auch 2025 t1 t2 t3 und testen dann komplett auf 2026 t1 also /train oder /raw / dctr
# featuers überarbeiten welche logische besser passen als z:B abstrc_LEN ersetzten durch zeit, citatzione, top Autoren
# Tabelle zeilen Baseline system bm25 feature a training feature b c etc dann mit den scores ndcg10 etc bpref
# zeit stempel bei citaztionen berücksichtigen iun csv datei von der Mail = Features
# schlagwörter aus dem abstract als features dafür librays mashterms

from ir_datasets import load
import ir_datasets_longeval

ds1 = load("longeval-sci-2026/snapshot-1")
ds2 = load("longeval-sci-2026/snapshot-2")
ds3 = load("longeval-sci-2026/snapshot-3")

print(ds1)
print(ds2)
print(ds3)

import ir_datasets

ds_train = ir_datasets.load(
    "longeval-sci-2026/snapshot-1/train/dctr"
)

print(ds_train.has_qrels())

ds = load("longeval-sci-2026/snapshot-1")

print(ds.has_qrels())
doc = next(ds.docs_iter())
print(doc)

!pip install -q pyterrier[java]

# Index für 2026 abgeändert auf ir_dataset anstelle von Local
from pathlib import Path
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

INDEX_DIR = Path("data/pt_index_v1_longeval")


def extract_date_parts(date_str: str):
    """
    Extrahiert year, month, yyyymm aus ISO-Datum.
    """
    year, month, yyyymm = "", "", ""

    if date_str and len(date_str) >= 7:
        y = date_str[:4]
        m = date_str[5:7]

        if y.isdigit():
            year = y
            if m.isdigit() and 1 <= int(m) <= 12:
                month = m
                yyyymm = f"{y}{m}"

    return year, month, yyyymm


def iter_longeval_docs():
    """
    Lädt Dokumente direkt aus ir_datasets (Longeval 2026).

    Indexiert:
      - docno = doc_id
      - text  = title + abstract
      - meta  = year, month, yyyymm
    """
    ds = ir_datasets.load("longeval-sci-2026/snapshot-1")

    for d in ds.docs_iter():
        docno = str(d.doc_id)

        title = (d.title or "").strip()
        abstract = (d.abstract or "").strip()
        text = (title + "\n\n" + abstract).strip()

        if not text:
            continue

        year, month, yyyymm = extract_date_parts(d.publishedDate)

        yield {
            "docno": docno,
            "text": text,
            "year": year,
            "month": month,
            "yyyymm": yyyymm
        }


def main():
    if not pt.java.started():
        pt.java.init()

    index_path = INDEX_DIR.resolve()

    # sauberer Neustart (wichtig!)
    if index_path.exists():
        import shutil
        shutil.rmtree(index_path)

    index_path.mkdir(parents=True, exist_ok=True)

    print(f"[INDEX] Baue neuen Longeval-Index in: {index_path}")

    indexer = pt.IterDictIndexer(
        str(index_path),
        meta={"docno": 40, "year": 4, "month": 2, "yyyymm": 6},
        text_attrs=["text"],
        overwrite=True
    )

    index_ref = indexer.index(iter_longeval_docs())

    print("[INDEX] Fertig! IndexRef:", index_ref)


if __name__ == "__main__":
    main()

# -*- coding: utf-8 INDEX SNAPSHOT 2-*-
from pathlib import Path
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

INDEX_DIR = Path("data/pt_index_v2_longeval")


def extract_date_parts(date_str: str):
    """
    Extrahiert year, month, yyyymm aus ISO-Datum.
    """
    year, month, yyyymm = "", "", ""

    if date_str and len(date_str) >= 7:
        y = date_str[:4]
        m = date_str[5:7]

        if y.isdigit():
            year = y
            if m.isdigit() and 1 <= int(m) <= 12:
                month = m
                yyyymm = f"{y}{m}"

    return year, month, yyyymm


def iter_longeval_docs():
    """
    Lädt Dokumente direkt aus ir_datasets (Longeval 2026).
    Kombiniert Snapshot 1 und Snapshot 2, um den vollen Korpus für Tests zu haben.

    Indexiert:
      - docno = doc_id
      - text  = title + abstract
      - meta  = year, month, yyyymm
    """
    # Beide Datensätze laden, damit der Index vollständig ist
    datasets = [
        "longeval-sci-2026/snapshot-1",
        "longeval-sci-2026/snapshot-2"
    ]

    seen_docnos = set()

    for ds_name in datasets:
        print(f"[INDEX] Lade Dokumente aus: {ds_name}...")
        ds = ir_datasets.load(ds_name)

        for d in ds.docs_iter():
            docno = str(d.doc_id)

            # Verhindere doppelte Indexierung von Dokumenten
            if docno in seen_docnos:
                continue

            seen_docnos.add(docno)

            title = (d.title or "").strip()
            abstract = (d.abstract or "").strip()
            text = (title + "\n\n" + abstract).strip()

            if not text:
                continue

            # Sicherstellen, dass das Attribut existiert
            published_date = getattr(d, 'publishedDate', '')
            year, month, yyyymm = extract_date_parts(published_date)

            yield {
                "docno": docno,
                "text": text,
                "year": year,
                "month": month,
                "yyyymm": yyyymm
            }


def main():
    if not pt.java.started():
        pt.java.init()

    index_path = INDEX_DIR.resolve()

    # sauberer Neustart (wichtig!)
    if index_path.exists():
        import shutil
        shutil.rmtree(index_path)

    index_path.mkdir(parents=True, exist_ok=True)

    print(f"[INDEX] Baue neuen kombinierten Longeval-Index in: {index_path}")

    indexer = pt.IterDictIndexer(
        str(index_path),
        meta={"docno": 40, "year": 4, "month": 2, "yyyymm": 6},
        text_attrs=["text"],
        overwrite=True
    )

    index_ref = indexer.index(iter_longeval_docs())

    print("[INDEX] Fertig! IndexRef:", index_ref)


if __name__ == "__main__":
    main()

# Evaluation
import pandas as pd
import pyterrier as pt
import ir_datasets

# Qrels laden (wie bisher)
qrels_df = pd.DataFrame([
    {"qid": q.query_id, "docno": q.doc_id, "label": int(q.relevance > 0)}
    for q in ir_datasets.load("longeval-sci-2026/snapshot-1/train/dctr").qrels_iter()
])

# BM25 Run laden
bm25_run = pd.read_json("runs/pt_bm25_test.jsonl", lines=True)
bm25_run = bm25_run.rename(columns={"doc_id": "docno"})
bm25_run = bm25_run[["qid", "docno", "score"]]

#  DER FIX: Filtere die Qrels auf die Queries, die im Test-Run existieren!
test_qids = bm25_run["qid"].unique()
qrels_test = qrels_df[qrels_df["qid"].isin(test_qids)]

print("BM25:", pt.Evaluate(bm25_run, qrels_test, metrics=["ndcg_cut_10"]))

# Hybrid Runs
for alpha in [0.05, 0.1, 0.2, 0.3]:
    run = pd.read_json(f"runs/pt_hybrid_alpha_{alpha}.jsonl", lines=True)
    run = run.rename(columns={"doc_id": "docno"})
    run = run[["qid", "docno", "score"]]

    print(f"Hybrid alpha={alpha}:",
          pt.Evaluate(run, qrels_test, metrics=["ndcg_cut_10"])) # Nutze hier auch qrels_test!

import pandas as pd
from ir_datasets import load

# Citation Counts laden
citation_df = pd.read_csv(
    "/content/cited_doc_id_counts.csv"
)

print(citation_df.head())
print(citation_df.columns)

import pandas as pd
from ir_datasets import load

# -----------------------------
# Citation IDs laden für Snapshot 1
# -----------------------------

citation_df = pd.read_csv(
    "/content/cited_doc_id_counts.csv"
)

citation_ids = set(
    citation_df["doc_id"].astype(str)
)

print("Citation IDs:", len(citation_ids))

# -----------------------------
# LongEval IDs laden
# -----------------------------

ds = load(
    "longeval-sci-2026/snapshot-1/train/raw"
)

longeval_ids = set()

for i, doc in enumerate(ds.docs_iter()):

    if i % 100000 == 0:
        print("processed:", i)

    longeval_ids.add(str(doc.doc_id))

print("LongEval IDs:", len(longeval_ids))

# -----------------------------
# Schnittmenge berechnen
# -----------------------------

intersection = citation_ids.intersection(
    longeval_ids
)

print("\nMatching IDs:", len(intersection))

# -----------------------------
# Coverage berechnen
# -----------------------------

coverage = (
    len(intersection) / len(longeval_ids)
)

print("\nCoverage over LongEval docs:")
print(f"{coverage:.4f}")

# -----------------------------
# Beispiele anzeigen
# -----------------------------

print("\nBeispiel-Matches:")
print(list(intersection)[:10])

import pandas as pd
from ir_datasets import load

# -----------------------------
# Citation IDs laden für SNapshot 2
# -----------------------------

citation_df = pd.read_csv(
    "/content/cited_doc_id_counts.csv"
)

citation_ids = set(
    citation_df["doc_id"].astype(str)
)

print("Citation IDs:", len(citation_ids))

# -----------------------------
# LongEval IDs laden
# Snapshot 1 + Snapshot 2
# -----------------------------

datasets = [
    "longeval-sci-2026/snapshot-1",
    "longeval-sci-2026/snapshot-2"
]

longeval_ids = set()

for ds_name in datasets:

    print(f"\nLade: {ds_name}")

    ds = load(ds_name)

    for i, doc in enumerate(ds.docs_iter()):

        if i % 100000 == 0:
            print("processed:", i)

        longeval_ids.add(str(doc.doc_id))

print("\nLongEval IDs:", len(longeval_ids))

# -----------------------------
# Schnittmenge berechnen
# -----------------------------

intersection = citation_ids.intersection(
    longeval_ids
)

print("\nMatching IDs:", len(intersection))

# -----------------------------
# Coverage berechnen
# -----------------------------

coverage = (
    len(intersection) / len(longeval_ids)
)

print("\nCoverage over combined LongEval docs:")
print(f"{coverage:.4f}")

# -----------------------------
# Beispiele anzeigen
# -----------------------------

print("\nBeispiel-Matches:")
print(list(intersection)[:10])

# Citation IDs, die NICHT im Snapshot existieren

missing_in_longeval = (
    citation_ids - longeval_ids
)

print("Nicht im LongEval Snapshot:")
print(len(missing_in_longeval))

# Anteil berechnen
ratio = (
    len(missing_in_longeval)
    / len(citation_ids)
)

print("\nAnteil fehlend:")
print(f"{ratio:.4f}")

# Beispiele
print("\nBeispiele:")
print(list(missing_in_longeval)[:20])

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*- SNAPSHOT1
from pathlib import Path
import json
import re
import pandas as pd
import numpy as np
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

# --- IMPORTS FÜR DENSE ---
import torch
from sentence_transformers import SentenceTransformer, util

INDEX_DIR = Path("data/pt_index_v1_longeval")
RUN_BM25_TEST = Path("runs/pt_bm25_test.jsonl")
RUN_LTR_TEST  = Path("runs/pt_ltr_test.jsonl")

# --- CITATION FEATURES ---
CITATION_CSV = "/content/cited_doc_id_counts.csv"

# --- OPTIMIERTE HYPERPARAMETER ---
CAND_TOPK = 1000
TRAIN_TOPK = 500

TEST_FRAC = 0.2
SEED = 42

MODEL_NUM_LEAVES = 15
MODEL_NUM_TREES = 300
MODEL_LEARNING_RATE = 0.03


def qlen(text: str) -> int:
    return len(re.findall(r"\w+", text.lower()))

def ensure_java():
    if not pt.java.started():
        pt.java.init()

def write_run_jsonl(df: pd.DataFrame, out_path: Path, score_col: str):
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:
        for row in df.itertuples(index=False):
            f.write(json.dumps({
                "qid": str(row.qid),
                "doc_id": str(row.docno),
                "rank": int(row.new_rank),
                "score": float(getattr(row, score_col)),
            }) + "\n")

# =========================
# QUERY CLEANING
# =========================
def clean_query(q: str) -> str:
    q = q.lower()
    q = re.sub(r'[^a-z0-9\s]', ' ', q)
    q = re.sub(r'\s+', ' ', q)
    return q.strip()

# =========================
# META INDEX (Recency)
# =========================
def build_meta_lookup(index_path: Path):
    index = pt.IndexFactory.of(str(index_path.resolve()))
    meta = index.getMetaIndex()

    def get_yyyymm(docid):
        try:
            val = meta.getItem("yyyymm", int(docid))
            return int(val) if val and str(val).isdigit() else 0
        except:
            return 0

    return get_yyyymm

# =========================
# DOC CACHES
# =========================
DOC_LENS_CACHE = None
DOC_TEXT_CACHE = None
DOC_TITLE_CACHE = None

def build_doc_caches(ds_docs):
    global DOC_LENS_CACHE, DOC_TEXT_CACHE, DOC_TITLE_CACHE

    if DOC_LENS_CACHE is not None:
        return DOC_LENS_CACHE, DOC_TEXT_CACHE, DOC_TITLE_CACHE

    DOC_LENS_CACHE = {}
    DOC_TEXT_CACHE = {}
    DOC_TITLE_CACHE = {}

    for d in ds_docs.docs_iter():

        title = (d.title or "").lower()
        abstract = (d.abstract or "").lower()

        text = title + " " + abstract

        DOC_LENS_CACHE[d.doc_id] = len(text.split())
        DOC_TEXT_CACHE[d.doc_id] = text
        DOC_TITLE_CACHE[d.doc_id] = title

    return DOC_LENS_CACHE, DOC_TEXT_CACHE, DOC_TITLE_CACHE

# =========================
# CITATION FEATURES
# =========================
CITATION_FEATURES = None

def load_citation_features(csv_path=CITATION_CSV):

    global CITATION_FEATURES

    if CITATION_FEATURES is not None:
        return CITATION_FEATURES

    print(">> Lade Citation Features...")

    df = pd.read_csv(csv_path)

    df["doc_id"] = df["doc_id"].astype(str)

    # Binary feature
    #df["f_has_citations"] = (
      #  df["citation_count"] > 0
   # ).astype(int)

    # Log feature
    df["f_log_citation_count"] = np.log1p(
        df["citation_count"]
    )

  #  citation_count_map = dict(
   #     zip(df["doc_id"], df["citation_count"])
  #  )

    log_citation_map = dict(
        zip(df["doc_id"], df["f_log_citation_count"])
    )

   # has_citation_map = dict(
    #    zip(df["doc_id"], df["f_has_citations"])
   # )

    CITATION_FEATURES = (
       # citation_count_map,
        log_citation_map,
       # has_citation_map
    )

    return CITATION_FEATURES

# =========================
# BASIS & TEXT FEATURES
# =========================
def add_features(
    cand: pd.DataFrame,
    qdf: pd.DataFrame,
    doc_lens,
    doc_texts,
    doc_titles,
    get_yyyymm,
   # citation_count_map,
    log_citation_map,
   # has_citation_map
):

    qlen_map = dict(
        zip(qdf["qid"], qdf["query"].map(qlen))
    )

    cand["f_qlen"] = (
        cand["qid"]
        .map(qlen_map)
        .fillna(0)
        .astype(int)
    )

    cand["f_bm25"] = cand["score"].astype(float)

    cand["f_doclen"] = (
        cand["docno"]
        .map(doc_lens)
        .fillna(0)
    )

    # =========================
    # Citation Features
    # =========================

   # cand["f_citation_count"] = (
      #  cand["docno"]
      #  .astype(str)
       # .map(citation_count_map)
      #  .fillna(0)
   # )

    cand["f_log_citation_count"] = (
        cand["docno"]
        .astype(str)
        .map(log_citation_map)
        .fillna(0)
    )

   # cand["f_has_citations"] = (
      #  cand["docno"]
       # .astype(str)
       # .map(has_citation_map)
       # .fillna(0)
  #  )

    # =========================
    # Recency
    # =========================

    cand["yyyymm"] = cand["docid"].map(get_yyyymm)

    def calc_age_in_months(yymm):

        if yymm == 0:
            return 999

        y = yymm // 100
        m = yymm % 100

        return (2026 - y) * 12 + (4 - m)

    cand["f_recency"] = (
        cand["yyyymm"]
        .map(calc_age_in_months)
    )

    # =========================
    # Overlap Features
    # =========================

    def calc_overlap(row, text_dict):

        q_terms = set(
            str(row["query"]).split()
        )

        doc_text = text_dict.get(
            row["docno"], ""
        )

        if not doc_text:
            return 0.0

        doc_terms = set(doc_text.split())

        overlap = len(
            q_terms.intersection(doc_terms)
        )

        return overlap / max(1, len(q_terms))

    if "query" not in cand.columns:
        cand = cand.merge(
            qdf[["qid", "query"]],
            on="qid",
            how="left"
        )

    cand["f_overlap"] = cand.apply(
        lambda r: calc_overlap(r, doc_texts),
        axis=1
    )

    cand["f_title_match"] = cand.apply(
        lambda r: calc_overlap(r, doc_titles),
        axis=1
    )

    cand.drop(columns=["yyyymm"], inplace=True)

    return cand

# =========================
# DENSE FEATURE
# =========================
DENSE_MODEL = None

def get_dense_model():

    global DENSE_MODEL

    if DENSE_MODEL is None:
        print(">> Lade SentenceTransformer Modell...")
        DENSE_MODEL = SentenceTransformer(
            "all-MiniLM-L6-v2"
        )

    return DENSE_MODEL

def add_dense_features_batched(
    cand: pd.DataFrame,
    qdf: pd.DataFrame,
    doc_texts: dict,
    batch_size=64
):

    model = get_dense_model()

    unique_qids = cand["qid"].unique()

    qid_to_query = dict(
        zip(qdf["qid"], qdf["query"])
    )

    q_texts = [
        qid_to_query[qid]
        for qid in unique_qids
    ]

    print(f">> Encodiere {len(q_texts)} Queries...")

    q_embs = model.encode(
        q_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=False
    )

    qid_to_emb = {
        qid: emb
        for qid, emb in zip(unique_qids, q_embs)
    }

    unique_docnos = cand["docno"].unique()

    d_texts = [
        doc_texts.get(d, "")[:1500]
        for d in unique_docnos
    ]

    print(f">> Encodiere {len(d_texts)} Dokumente...")

    d_embs = model.encode(
        d_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=True
    )

    docno_to_emb = {
        docno: emb
        for docno, emb in zip(unique_docnos, d_embs)
    }

    print(">> Berechne Dense Scores...")

    dense_scores = []

    for _, row in cand.iterrows():

        q_e = qid_to_emb[row["qid"]]
        d_e = docno_to_emb[row["docno"]]

        score = util.cos_sim(q_e, d_e).item()

        dense_scores.append(score)

    cand["f_dense"] = dense_scores

    return cand

# =========================
# MAIN
# =========================
def main():

    ensure_java()

    print("Loading datasets...")

    ds_train = ir_datasets.load(
        "longeval-sci-2026/snapshot-1/train/dctr"
    )

    ds_docs = ir_datasets.load(
        "longeval-sci-2026/snapshot-1"
    )

    # =========================
    # QUERIES + QRELS
    # =========================

    queries = pd.DataFrame([
        {
            "qid": q.query_id,
            "query": clean_query(q.text)
        }
        for q in ds_train.queries_iter()
    ])

    qrels = pd.DataFrame([
        {
            "qid": q.query_id,
            "docno": q.doc_id,
            "label": int(q.relevance)
        }
        for q in ds_train.qrels_iter()
    ])

    # =========================
    # SPLIT
    # =========================

    qids = queries["qid"].tolist()

    qids_shuffled = (
        pd.Series(qids)
        .sample(frac=1.0, random_state=SEED)
        .tolist()
    )

    cut = int(
        len(qids_shuffled) * (1 - TEST_FRAC)
    )

    train_qids = set(qids_shuffled[:cut])
    test_qids = set(qids_shuffled[cut:])

    q_train = queries[
        queries["qid"].isin(train_qids)
    ].reset_index(drop=True)

    q_test = queries[
        queries["qid"].isin(test_qids)
    ].reset_index(drop=True)

    print(
        f"SPLIT: train={len(q_train)} | test={len(q_test)}"
    )

    # =========================
    # INDEX
    # =========================

    if not INDEX_DIR.exists():
        raise FileNotFoundError(
            "Index fehlt!"
        )

    index_path = str(INDEX_DIR.resolve())

    print("USING INDEX:", index_path)

    index = pt.IndexFactory.of(index_path)

    bm25 = pt.terrier.Retriever(
        index,
        wmodel="BM25",
        num_results=CAND_TOPK
    )

    # =========================
    # RETRIEVAL
    # =========================

    print("\n--- RETRIEVAL ---")

    cand_train = bm25.transform(q_train)
    cand_test = bm25.transform(q_test)

    # =========================
    # FEATURE EXTRACTION
    # =========================

    print("\n--- FEATURE EXTRACTION ---")

    doc_lens, doc_texts, doc_titles = (
        build_doc_caches(ds_docs)
    )

    get_yyyymm = build_meta_lookup(
        INDEX_DIR
    )

    (
       # citation_count_map,
        log_citation_map,
       # has_citation_map
    ) = load_citation_features()

    cand_train = add_features(
        cand_train,
        q_train,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
       # citation_count_map,
        log_citation_map,
       # has_citation_map
    )

    cand_test = add_features(
        cand_test,
        q_test,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
       # citation_count_map,
        log_citation_map,
       # has_citation_map
    )

    # Dense Features
    cand_train = add_dense_features_batched(
        cand_train,
        q_train,
        doc_texts
    )

    cand_test = add_dense_features_batched(
        cand_test,
        q_test,
        doc_texts
    )

    # =========================
    # TRAIN LTR
    # =========================

    print("\n--- LTR TRAINING ---")

    train_df = cand_train.merge(
        qrels,
        on=["qid", "docno"],
        how="left"
    )

    train_df["label"] = (
        train_df["label"]
        .fillna(0)
    )

    train_df = (
        train_df
        .sort_values(
            ["qid", "score"],
            ascending=[True, False]
        )
        .groupby("qid")
        .head(TRAIN_TOPK)
    )

    feature_cols = [
        "f_bm25",
        "f_qlen",
        "f_doclen",
        "f_recency",
        "f_overlap",
        "f_title_match",
        "f_dense",

        # Citation Features
       # "f_citation_count",
        "f_log_citation_count",
       # "f_has_citations"
    ]

    X = train_df[feature_cols]
    y = train_df["label"]

    group_sizes = (
        train_df
        .groupby("qid")
        .size()
        .tolist()
    )

    import lightgbm as lgb

    lgb_train = lgb.Dataset(
        X,
        label=y,
        group=group_sizes,
        free_raw_data=False
    )

    params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_eval_at": [10],
        "learning_rate": MODEL_LEARNING_RATE,
        "num_leaves": MODEL_NUM_LEAVES,
        "verbosity": -1,
    }

    model = lgb.train(
        params,
        lgb_train,
        num_boost_round=MODEL_NUM_TREES
    )

    print("\n=== Feature Importance ===")

    importance = model.feature_importance(
        importance_type="gain"
    )

    for feat, imp in sorted(
        zip(feature_cols, importance),
        key=lambda x: x[1],
        reverse=True
    ):
        print(f"{feat:25s}: {imp:.2f}")

    print("==========================\n")

    # =========================
    # SCORING
    # =========================

    print("--- SCORING & OUTPUT ---")

    bm25_test = cand_test.sort_values(
        ["qid", "score"],
        ascending=[True, False]
    )

    bm25_test["new_rank"] = (
        bm25_test
        .groupby("qid")
        .cumcount()
    )

    write_run_jsonl(
        bm25_test,
        RUN_BM25_TEST,
        "score"
    )

    ltr_test_base = cand_test.copy()

    ltr_test_base["ltr_score"] = model.predict(
        ltr_test_base[feature_cols]
    )

    ltr_test_base["bm25_norm"] = (
        ltr_test_base
        .groupby("qid")["score"]
        .transform(
            lambda x:
            (x - x.min()) / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    ltr_test_base["ltr_norm"] = (
        ltr_test_base
        .groupby("qid")["ltr_score"]
        .transform(
            lambda x:
            (x - x.min()) / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    for alpha in [0.1, 0.2, 0.3, 0.4, 0.5]:

        ltr_test = ltr_test_base.copy()

        ltr_test["hybrid_score"] = (
            (1 - alpha) * ltr_test["bm25_norm"]
            + alpha * ltr_test["ltr_norm"]
        )

        ltr_test = ltr_test.sort_values(
            ["qid", "hybrid_score"],
            ascending=[True, False]
        )

        ltr_test["new_rank"] = (
            ltr_test
            .groupby("qid")
            .cumcount()
        )

        out_path = Path(
            f"runs/pt_hybrid_alpha_{alpha}.jsonl"
        )

        write_run_jsonl(
            ltr_test,
            out_path,
            "hybrid_score"
        )

    # =========================
    # EVALUATION
    # =========================

    print("\n--- EVALUATION ---")

    test_qids_arr = bm25_test["qid"].unique()

    qrels_test = qrels[
        qrels["qid"].isin(test_qids_arr)
    ]

    eval_bm25 = pt.Evaluate(
        bm25_test.rename(columns={"doc_id": "docno"}),
        qrels_test,
        metrics=["ndcg_cut_10"]
    )

    print(f"BM25: {eval_bm25}")

    for alpha in [0.1, 0.2, 0.3, 0.4, 0.5]:

        run = pd.read_json(
            f"runs/pt_hybrid_alpha_{alpha}.jsonl",
            lines=True
        ).rename(columns={"doc_id": "docno"})

        eval_ltr = pt.Evaluate(
            run,
            qrels_test,
            metrics=["ndcg_cut_10"]
        )

        print(
            f"Hybrid alpha={alpha}: {eval_ltr}"
        )

if __name__ == "__main__":
    main()

# -*- coding: utf-8 -*- SNAPSHOT 2
from pathlib import Path
import json
import re
import pandas as pd
import numpy as np
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

# --- IMPORTS FÜR DENSE ---
import torch
from sentence_transformers import SentenceTransformer, util

INDEX_DIR = Path("data/pt_index_v2_longeval")

# --- OUTPUT RUNS ---
RUN_BM25 = Path("runs/snapshot2_bm25.jsonl")
RUN_HYBRID = Path("runs/snapshot2_hybrid_alpha_015.jsonl")

# --- CITATION FEATURES ---
CITATION_CSV = "/content/cited_doc_id_counts.csv"

# --- HYPERPARAMETER ---
CAND_TOPK = 1000
TRAIN_TOPK = 500

MODEL_NUM_LEAVES = 15
MODEL_NUM_TREES = 300
MODEL_LEARNING_RATE = 0.03

# Bester Wert aus Snapshot-1 Evaluation
BEST_ALPHA = 0.15


def qlen(text: str) -> int:
    return len(re.findall(r"\w+", text.lower()))


def ensure_java():
    if not pt.java.started():
        pt.java.init()


def write_run_jsonl(df: pd.DataFrame, out_path: Path, score_col: str):

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:

        for row in df.itertuples(index=False):

            f.write(json.dumps({
                "qid": str(row.qid),
                "doc_id": str(row.docno),
                "rank": int(row.new_rank),
                "score": float(getattr(row, score_col)),
            }) + "\n")


# =========================
# QUERY CLEANING
# =========================
def clean_query(q: str):

    q = q.lower()
    q = re.sub(r'[^a-z0-9\s]', ' ', q)
    q = re.sub(r'\s+', ' ', q)

    return q.strip()


# =========================
# META INDEX (Recency)
# =========================
def build_meta_lookup(index_path: Path):

    index = pt.IndexFactory.of(str(index_path.resolve()))
    meta = index.getMetaIndex()

    def get_yyyymm(docid):

        try:
            val = meta.getItem("yyyymm", int(docid))

            return int(val) if val and str(val).isdigit() else 0

        except:
            return 0

    return get_yyyymm


# =========================
# DOC CACHES
# =========================
DOC_LENS_CACHE = None
DOC_TEXT_CACHE = None
DOC_TITLE_CACHE = None


def build_doc_caches(datasets):

    global DOC_LENS_CACHE
    global DOC_TEXT_CACHE
    global DOC_TITLE_CACHE

    if DOC_LENS_CACHE is not None:
        return DOC_LENS_CACHE, DOC_TEXT_CACHE, DOC_TITLE_CACHE

    DOC_LENS_CACHE = {}
    DOC_TEXT_CACHE = {}
    DOC_TITLE_CACHE = {}

    for ds in datasets:

        for d in ds.docs_iter():

            if d.doc_id in DOC_LENS_CACHE:
                continue

            title = (d.title or "").lower()
            abstract = (d.abstract or "").lower()

            text = title + " " + abstract

            DOC_LENS_CACHE[d.doc_id] = len(text.split())
            DOC_TEXT_CACHE[d.doc_id] = text
            DOC_TITLE_CACHE[d.doc_id] = title

    return DOC_LENS_CACHE, DOC_TEXT_CACHE, DOC_TITLE_CACHE


# =========================
# CITATION FEATURES
# =========================
CITATION_FEATURES = None


def load_citation_features(csv_path=CITATION_CSV):

    global CITATION_FEATURES

    if CITATION_FEATURES is not None:
        return CITATION_FEATURES

    print(">> Lade Citation Features...")

    df = pd.read_csv(csv_path)

    df["doc_id"] = df["doc_id"].astype(str)

    df["f_log_citation_count"] = np.log1p(
        df["citation_count"]
    )

    log_citation_map = dict(
        zip(df["doc_id"], df["f_log_citation_count"])
    )

    CITATION_FEATURES = (
        log_citation_map,
    )

    return CITATION_FEATURES


# =========================
# FEATURE EXTRACTION
# =========================
def add_features(
    cand,
    qdf,
    doc_lens,
    doc_texts,
    doc_titles,
    get_yyyymm,
    log_citation_map
):

    qlen_map = dict(
        zip(qdf["qid"], qdf["query"].map(qlen))
    )

    cand["f_qlen"] = (
        cand["qid"]
        .map(qlen_map)
        .fillna(0)
        .astype(int)
    )

    cand["f_bm25"] = cand["score"].astype(float)

    cand["f_doclen"] = (
        cand["docno"]
        .map(doc_lens)
        .fillna(0)
    )

    cand["f_log_citation_count"] = (
        cand["docno"]
        .astype(str)
        .map(log_citation_map)
        .fillna(0)
    )

    cand["yyyymm"] = cand["docid"].map(get_yyyymm)

    def calc_age_in_months(yymm):

        if yymm == 0:
            return 999

        y = yymm // 100
        m = yymm % 100

        return (2026 - y) * 12 + (4 - m)

    cand["f_recency"] = (
        cand["yyyymm"]
        .map(calc_age_in_months)
    )

    def calc_overlap(row, text_dict):

        q_terms = set(
            str(row["query"]).split()
        )

        doc_text = text_dict.get(
            row["docno"], ""
        )

        if not doc_text:
            return 0.0

        doc_terms = set(doc_text.split())

        overlap = len(
            q_terms.intersection(doc_terms)
        )

        return overlap / max(1, len(q_terms))

    if "query" not in cand.columns:

        cand = cand.merge(
            qdf[["qid", "query"]],
            on="qid",
            how="left"
        )

    cand["f_overlap"] = cand.apply(
        lambda r: calc_overlap(r, doc_texts),
        axis=1
    )

    cand["f_title_match"] = cand.apply(
        lambda r: calc_overlap(r, doc_titles),
        axis=1
    )

    cand.drop(columns=["yyyymm"], inplace=True)

    return cand


# =========================
# DENSE FEATURES
# =========================
DENSE_MODEL = None


def get_dense_model():

    global DENSE_MODEL

    if DENSE_MODEL is None:

        print(">> Lade SentenceTransformer Modell...")

        DENSE_MODEL = SentenceTransformer(
            "all-MiniLM-L6-v2"
        )

    return DENSE_MODEL


def add_dense_features_batched(
    cand,
    qdf,
    doc_texts,
    batch_size=64
):

    model = get_dense_model()

    unique_qids = cand["qid"].unique()

    qid_to_query = dict(
        zip(qdf["qid"], qdf["query"])
    )

    q_texts = [
        qid_to_query[qid]
        for qid in unique_qids
    ]

    print(f">> Encodiere {len(q_texts)} Queries...")

    q_embs = model.encode(
        q_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=False
    )

    qid_to_emb = {
        qid: emb
        for qid, emb in zip(unique_qids, q_embs)
    }

    unique_docnos = cand["docno"].unique()

    d_texts = [
        doc_texts.get(d, "")[:1500]
        for d in unique_docnos
    ]

    print(f">> Encodiere {len(d_texts)} Dokumente...")

    d_embs = model.encode(
        d_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=True
    )

    docno_to_emb = {
        docno: emb
        for docno, emb in zip(unique_docnos, d_embs)
    }

    print(">> Berechne Dense Scores...")

    dense_scores = []

    for _, row in cand.iterrows():

        q_e = qid_to_emb[row["qid"]]
        d_e = docno_to_emb[row["docno"]]

        score = util.cos_sim(q_e, d_e).item()

        dense_scores.append(score)

    cand["f_dense"] = dense_scores

    return cand


# =========================
# MAIN
# =========================
def main():

    ensure_java()

    print("Loading datasets...")

    # TRAINING
    ds_train = ir_datasets.load(
        "longeval-sci-2026/snapshot-1/train/dctr"
    )

    ds_docs_train = ir_datasets.load(
        "longeval-sci-2026/snapshot-1"
    )

    # SNAPSHOT 2
    ds_test = ir_datasets.load(
        "longeval-sci-2026/snapshot-2"
    )

    ds_docs_test = ir_datasets.load(
        "longeval-sci-2026/snapshot-2"
    )

    # =========================
    # QUERIES + QRELS
    # =========================

    q_train = pd.DataFrame([
        {
            "qid": q.query_id,
            "query": clean_query(q.text)
        }
        for q in ds_train.queries_iter()
    ])

    qrels = pd.DataFrame([
        {
            "qid": q.query_id,
            "docno": q.doc_id,
            "label": int(q.relevance)
        }
        for q in ds_train.qrels_iter()
    ])

    q_test = pd.DataFrame([
        {
            "qid": q.query_id,
            "query": clean_query(q.text)
        }
        for q in ds_test.queries_iter()
    ])

    print(
        f"Train Queries: {len(q_train)} | "
        f"Snapshot2 Queries: {len(q_test)}"
    )

    # =========================
    # INDEX
    # =========================

    if not INDEX_DIR.exists():
        raise FileNotFoundError("Index fehlt!")

    index_path = str(INDEX_DIR.resolve())

    print("USING INDEX:", index_path)

    index = pt.IndexFactory.of(index_path)

    bm25 = pt.terrier.Retriever(
        index,
        wmodel="BM25",
        num_results=CAND_TOPK
    )

    # =========================
    # RETRIEVAL
    # =========================

    print("\n--- RETRIEVAL ---")

    cand_train = bm25.transform(q_train)
    cand_test = bm25.transform(q_test)

    # =========================
    # FEATURE EXTRACTION
    # =========================

    print("\n--- FEATURE EXTRACTION ---")

    doc_lens, doc_texts, doc_titles = (
        build_doc_caches([
            ds_docs_train,
            ds_docs_test
        ])
    )

    get_yyyymm = build_meta_lookup(
        INDEX_DIR
    )

    (
        log_citation_map,
    ) = load_citation_features()

    cand_train = add_features(
        cand_train,
        q_train,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
        log_citation_map
    )

    cand_test = add_features(
        cand_test,
        q_test,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
        log_citation_map
    )

    # Dense Features
    cand_train = add_dense_features_batched(
        cand_train,
        q_train,
        doc_texts
    )

    cand_test = add_dense_features_batched(
        cand_test,
        q_test,
        doc_texts
    )

    # =========================
    # TRAIN LTR
    # =========================

    print("\n--- TRAIN LTR ---")

    train_df = cand_train.merge(
        qrels,
        on=["qid", "docno"],
        how="left"
    )

    train_df["label"] = (
        train_df["label"]
        .fillna(0)
    )

    train_df = (
        train_df
        .sort_values(
            ["qid", "score"],
            ascending=[True, False]
        )
        .groupby("qid")
        .head(TRAIN_TOPK)
    )

    feature_cols = [
        "f_bm25",
        "f_qlen",
        "f_doclen",
        "f_recency",
        "f_overlap",
        "f_title_match",
        "f_dense",
        "f_log_citation_count",
    ]

    X = train_df[feature_cols]
    y = train_df["label"]

    group_sizes = (
        train_df
        .groupby("qid")
        .size()
        .tolist()
    )

    import lightgbm as lgb

    lgb_train = lgb.Dataset(
        X,
        label=y,
        group=group_sizes,
        free_raw_data=False
    )

    params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_eval_at": [10],
        "learning_rate": MODEL_LEARNING_RATE,
        "num_leaves": MODEL_NUM_LEAVES,
        "verbosity": -1,
    }

    model = lgb.train(
        params,
        lgb_train,
        num_boost_round=MODEL_NUM_TREES
    )

    # =========================
    # SNAPSHOT 2 SCORING
    # =========================

    print("\n--- SNAPSHOT 2 INFERENCE ---")

    # BM25
    bm25_test = cand_test.sort_values(
        ["qid", "score"],
        ascending=[True, False]
    )

    bm25_test["new_rank"] = (
        bm25_test
        .groupby("qid")
        .cumcount()
    )

    write_run_jsonl(
        bm25_test,
        RUN_BM25,
        "score"
    )

    # LTR
    ltr_test = cand_test.copy()

    ltr_test["ltr_score"] = model.predict(
        ltr_test[feature_cols]
    )

    ltr_test["bm25_norm"] = (
        ltr_test
        .groupby("qid")["score"]
        .transform(
            lambda x:
            (x - x.min()) / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    ltr_test["ltr_norm"] = (
        ltr_test
        .groupby("qid")["ltr_score"]
        .transform(
            lambda x:
            (x - x.min()) / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    # Hybrid
    ltr_test["hybrid_score"] = (
        (1 - BEST_ALPHA) * ltr_test["bm25_norm"]
        + BEST_ALPHA * ltr_test["ltr_norm"]
    )

    ltr_test = ltr_test.sort_values(
        ["qid", "hybrid_score"],
        ascending=[True, False]
    )

    ltr_test["new_rank"] = (
        ltr_test
        .groupby("qid")
        .cumcount()
    )

    write_run_jsonl(
        ltr_test,
        RUN_HYBRID,
        "hybrid_score"
    )

    print("\nFertig!")
    print(f"BM25 Run: {RUN_BM25}")
    print(f"Hybrid Run: {RUN_HYBRID}")

    print("\nHinweis:")
    print("Snapshot 2 besitzt keine öffentlichen Qrels.")
    print("Daher wird keine nDCG@10 Evaluation berechnet.")


if __name__ == "__main__":
    main()

# -*- coding: utf-8 -*-
from pathlib import Path
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

# =========================================
# INDEX: SNAPSHOT 1 + 2 + 3
# =========================================

INDEX_DIR = Path("data/pt_index_v3_longeval")


def extract_date_parts(date_str: str):
    """
    Extrahiert:
      - year
      - month
      - yyyymm

    aus ISO-Datum.
    """

    year, month, yyyymm = "", "", ""

    if date_str and len(date_str) >= 7:

        y = date_str[:4]
        m = date_str[5:7]

        if y.isdigit():

            year = y

            if m.isdigit() and 1 <= int(m) <= 12:

                month = m
                yyyymm = f"{y}{m}"

    return year, month, yyyymm


def iter_longeval_docs():
    """
    Kombiniert:
      - Snapshot 1
      - Snapshot 2
      - Snapshot 3

    zu einem vollständigen temporalen Korpus.

    Indexiert:
      - docno
      - text
      - year
      - month
      - yyyymm
    """

    datasets = [
        "longeval-sci-2026/snapshot-1",
        "longeval-sci-2026/snapshot-2",
        "longeval-sci-2026/snapshot-3"
    ]

    seen_docnos = set()

    for ds_name in datasets:

        print(f"\n[INDEX] Lade Dokumente aus: {ds_name}")

        ds = ir_datasets.load(ds_name)

        for i, d in enumerate(ds.docs_iter()):

            if i % 100000 == 0:
                print(f"processed: {i}")

            docno = str(d.doc_id)

            # Doppelte Dokumente verhindern
            if docno in seen_docnos:
                continue

            seen_docnos.add(docno)

            title = (d.title or "").strip()
            abstract = (d.abstract or "").strip()

            text = (
                title + "\n\n" + abstract
            ).strip()

            if not text:
                continue

            # Veröffentlichungsdatum
            published_date = getattr(
                d,
                "publishedDate",
                ""
            )

            year, month, yyyymm = (
                extract_date_parts(
                    published_date
                )
            )

            yield {
                "docno": docno,
                "text": text,
                "year": year,
                "month": month,
                "yyyymm": yyyymm
            }


def main():

    if not pt.java.started():
        pt.java.init()

    index_path = INDEX_DIR.resolve()

    # =========================================
    # CLEAN REBUILD
    # =========================================

    if index_path.exists():

        print(
            f"\n[INDEX] Lösche alten Index: {index_path}"
        )

        import shutil
        shutil.rmtree(index_path)

    index_path.mkdir(
        parents=True,
        exist_ok=True
    )

    print(
        f"\n[INDEX] Baue neuen kombinierten "
        f"Longeval-Index in:\n{index_path}"
    )

    # =========================================
    # INDEXER
    # =========================================

    indexer = pt.IterDictIndexer(
        str(index_path),

        meta={
            "docno": 40,
            "year": 4,
            "month": 2,
            "yyyymm": 6
        },

        text_attrs=["text"],

        overwrite=True
    )

    # =========================================
    # BUILD INDEX
    # =========================================

    index_ref = indexer.index(
        iter_longeval_docs()
    )

    print("\n[INDEX] Fertig!")
    print("IndexRef:", index_ref)

    print(
        f"\n[Index gespeichert unter]\n{INDEX_DIR}"
    )


if __name__ == "__main__":
    main()

import pandas as pd
from ir_datasets import load

# =========================================
# CITATION COVERAGE
# SNAPSHOT 1 + 2 + 3
# =========================================

# -----------------------------
# Citation IDs laden
# -----------------------------

citation_df = pd.read_csv(
    "/content/cited_doc_id_counts.csv"
)

citation_ids = set(
    citation_df["doc_id"].astype(str)
)

print("Citation IDs:", len(citation_ids))

# -----------------------------
# LongEval IDs laden
# Snapshot 1 + 2 + 3
# -----------------------------

datasets = [
    "longeval-sci-2026/snapshot-1",
    "longeval-sci-2026/snapshot-2",
    "longeval-sci-2026/snapshot-3"
]

longeval_ids = set()

for ds_name in datasets:

    print(f"\nLade: {ds_name}")

    ds = load(ds_name)

    for i, doc in enumerate(ds.docs_iter()):

        if i % 100000 == 0:
            print("processed:", i)

        longeval_ids.add(
            str(doc.doc_id)
        )

print("\nLongEval IDs:", len(longeval_ids))

# -----------------------------
# Schnittmenge berechnen
# -----------------------------

intersection = citation_ids.intersection(
    longeval_ids
)

print("\nMatching IDs:", len(intersection))

# -----------------------------
# Coverage berechnen
# -----------------------------

coverage = (
    len(intersection)
    / len(longeval_ids)
)

print("\nCoverage over combined LongEval docs:")
print(f"{coverage:.4f}")

# -----------------------------
# Fehlende Citation IDs
# -----------------------------

missing_in_longeval = (
    citation_ids - longeval_ids
)

print("\nNicht im LongEval Korpus:")
print(len(missing_in_longeval))

ratio = (
    len(missing_in_longeval)
    / len(citation_ids)
)

print("\nAnteil fehlend:")
print(f"{ratio:.4f}")

# -----------------------------
# Beispiele anzeigen
# -----------------------------

print("\nBeispiel-Matches:")
print(list(intersection)[:10])

print("\nBeispiele fehlende IDs:")
print(list(missing_in_longeval)[:20])

# -*- coding: utf-8 -*-
from pathlib import Path
import json
import re
import pandas as pd
import numpy as np
import pyterrier as pt
import ir_datasets
import ir_datasets_longeval

# --- IMPORTS FÜR DENSE ---
import torch
from sentence_transformers import SentenceTransformer, util

# =========================================
# INDEX SNAPSHOT 1 + 2 + 3
# =========================================

INDEX_DIR = Path("data/pt_index_v3_longeval")

# --- OUTPUT RUNS ---
RUN_BM25 = Path("runs/snapshot3_bm25.jsonl")
RUN_HYBRID = Path("runs/snapshot3_hybrid_alpha_015.jsonl")

# --- CITATION FEATURES ---
CITATION_CSV = "/content/cited_doc_id_counts.csv"

# --- HYPERPARAMETER ---
CAND_TOPK = 1000
TRAIN_TOPK = 500

MODEL_NUM_LEAVES = 15
MODEL_NUM_TREES = 300
MODEL_LEARNING_RATE = 0.03

# Bestes Alpha aus Snapshot-1 Evaluation
BEST_ALPHA = 0.15


def qlen(text: str) -> int:
    return len(re.findall(r"\w+", text.lower()))


def ensure_java():
    if not pt.java.started():
        pt.java.init()


def write_run_jsonl(df: pd.DataFrame, out_path: Path, score_col: str):

    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:

        for row in df.itertuples(index=False):

            f.write(json.dumps({
                "qid": str(row.qid),
                "doc_id": str(row.docno),
                "rank": int(row.new_rank),
                "score": float(getattr(row, score_col)),
            }) + "\n")


# =========================================
# QUERY CLEANING
# =========================================
def clean_query(q: str):

    q = q.lower()
    q = re.sub(r'[^a-z0-9\s]', ' ', q)
    q = re.sub(r'\s+', ' ', q)

    return q.strip()


# =========================================
# META INDEX
# =========================================
def build_meta_lookup(index_path: Path):

    index = pt.IndexFactory.of(
        str(index_path.resolve())
    )

    meta = index.getMetaIndex()

    def get_yyyymm(docid):

        try:

            val = meta.getItem(
                "yyyymm",
                int(docid)
            )

            return (
                int(val)
                if val and str(val).isdigit()
                else 0
            )

        except:
            return 0

    return get_yyyymm


# =========================================
# DOC CACHES
# =========================================
DOC_LENS_CACHE = None
DOC_TEXT_CACHE = None
DOC_TITLE_CACHE = None


def build_doc_caches(datasets):

    global DOC_LENS_CACHE
    global DOC_TEXT_CACHE
    global DOC_TITLE_CACHE

    if DOC_LENS_CACHE is not None:

        return (
            DOC_LENS_CACHE,
            DOC_TEXT_CACHE,
            DOC_TITLE_CACHE
        )

    DOC_LENS_CACHE = {}
    DOC_TEXT_CACHE = {}
    DOC_TITLE_CACHE = {}

    for ds in datasets:

        for d in ds.docs_iter():

            if d.doc_id in DOC_LENS_CACHE:
                continue

            title = (d.title or "").lower()
            abstract = (d.abstract or "").lower()

            text = title + " " + abstract

            DOC_LENS_CACHE[d.doc_id] = (
                len(text.split())
            )

            DOC_TEXT_CACHE[d.doc_id] = text
            DOC_TITLE_CACHE[d.doc_id] = title

    return (
        DOC_LENS_CACHE,
        DOC_TEXT_CACHE,
        DOC_TITLE_CACHE
    )


# =========================================
# CITATION FEATURES
# =========================================
CITATION_FEATURES = None


def load_citation_features(
    csv_path=CITATION_CSV
):

    global CITATION_FEATURES

    if CITATION_FEATURES is not None:
        return CITATION_FEATURES

    print(">> Lade Citation Features...")

    df = pd.read_csv(csv_path)

    df["doc_id"] = (
        df["doc_id"].astype(str)
    )

    df["f_log_citation_count"] = (
        np.log1p(df["citation_count"])
    )

    log_citation_map = dict(
        zip(
            df["doc_id"],
            df["f_log_citation_count"]
        )
    )

    CITATION_FEATURES = (
        log_citation_map,
    )

    return CITATION_FEATURES


# =========================================
# FEATURE EXTRACTION
# =========================================
def add_features(
    cand,
    qdf,
    doc_lens,
    doc_texts,
    doc_titles,
    get_yyyymm,
    log_citation_map
):

    qlen_map = dict(
        zip(
            qdf["qid"],
            qdf["query"].map(qlen)
        )
    )

    cand["f_qlen"] = (
        cand["qid"]
        .map(qlen_map)
        .fillna(0)
        .astype(int)
    )

    cand["f_bm25"] = (
        cand["score"].astype(float)
    )

    cand["f_doclen"] = (
        cand["docno"]
        .map(doc_lens)
        .fillna(0)
    )

    cand["f_log_citation_count"] = (
        cand["docno"]
        .astype(str)
        .map(log_citation_map)
        .fillna(0)
    )

    cand["yyyymm"] = (
        cand["docid"]
        .map(get_yyyymm)
    )

    def calc_age_in_months(yymm):

        if yymm == 0:
            return 999

        y = yymm // 100
        m = yymm % 100

        return (
            (2026 - y) * 12
            + (4 - m)
        )

    cand["f_recency"] = (
        cand["yyyymm"]
        .map(calc_age_in_months)
    )

    def calc_overlap(row, text_dict):

        q_terms = set(
            str(row["query"]).split()
        )

        doc_text = text_dict.get(
            row["docno"],
            ""
        )

        if not doc_text:
            return 0.0

        doc_terms = set(
            doc_text.split()
        )

        overlap = len(
            q_terms.intersection(doc_terms)
        )

        return overlap / max(
            1,
            len(q_terms)
        )

    if "query" not in cand.columns:

        cand = cand.merge(
            qdf[["qid", "query"]],
            on="qid",
            how="left"
        )

    cand["f_overlap"] = cand.apply(
        lambda r: calc_overlap(
            r,
            doc_texts
        ),
        axis=1
    )

    cand["f_title_match"] = cand.apply(
        lambda r: calc_overlap(
            r,
            doc_titles
        ),
        axis=1
    )

    cand.drop(
        columns=["yyyymm"],
        inplace=True
    )

    return cand


# =========================================
# DENSE FEATURES
# =========================================
DENSE_MODEL = None


def get_dense_model():

    global DENSE_MODEL

    if DENSE_MODEL is None:

        print(
            ">> Lade SentenceTransformer Modell..."
        )

        DENSE_MODEL = SentenceTransformer(
            "all-MiniLM-L6-v2"
        )

    return DENSE_MODEL


def add_dense_features_batched(
    cand,
    qdf,
    doc_texts,
    batch_size=64
):

    model = get_dense_model()

    unique_qids = (
        cand["qid"].unique()
    )

    qid_to_query = dict(
        zip(
            qdf["qid"],
            qdf["query"]
        )
    )

    q_texts = [
        qid_to_query[qid]
        for qid in unique_qids
    ]

    print(
        f">> Encodiere "
        f"{len(q_texts)} Queries..."
    )

    q_embs = model.encode(
        q_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=False
    )

    qid_to_emb = {
        qid: emb
        for qid, emb
        in zip(unique_qids, q_embs)
    }

    unique_docnos = (
        cand["docno"].unique()
    )

    d_texts = [
        doc_texts.get(d, "")[:1500]
        for d in unique_docnos
    ]

    print(
        f">> Encodiere "
        f"{len(d_texts)} Dokumente..."
    )

    d_embs = model.encode(
        d_texts,
        batch_size=batch_size,
        convert_to_tensor=True,
        show_progress_bar=True
    )

    docno_to_emb = {
        docno: emb
        for docno, emb
        in zip(unique_docnos, d_embs)
    }

    print(">> Berechne Dense Scores...")

    dense_scores = []

    for _, row in cand.iterrows():

        q_e = qid_to_emb[row["qid"]]
        d_e = docno_to_emb[row["docno"]]

        score = util.cos_sim(
            q_e,
            d_e
        ).item()

        dense_scores.append(score)

    cand["f_dense"] = dense_scores

    return cand


# =========================================
# MAIN
# =========================================
def main():

    ensure_java()

    print("Loading datasets...")

    # =====================================
    # TRAINING
    # =====================================

    ds_train = ir_datasets.load(
        "longeval-sci-2026/snapshot-1/train/dctr"
    )

    # =====================================
    # DOC CORPORA
    # =====================================

    ds_docs_s1 = ir_datasets.load(
        "longeval-sci-2026/snapshot-1"
    )

    ds_docs_s2 = ir_datasets.load(
        "longeval-sci-2026/snapshot-2"
    )

    ds_docs_s3 = ir_datasets.load(
        "longeval-sci-2026/snapshot-3"
    )

    # =====================================
    # SNAPSHOT 3 QUERIES
    # =====================================

    ds_test = ir_datasets.load(
        "longeval-sci-2026/snapshot-3"
    )

    # =====================================
    # QUERIES + QRELS
    # =====================================

    q_train = pd.DataFrame([
        {
            "qid": q.query_id,
            "query": clean_query(q.text)
        }
        for q in ds_train.queries_iter()
    ])

    qrels = pd.DataFrame([
        {
            "qid": q.query_id,
            "docno": q.doc_id,
            "label": int(q.relevance)
        }
        for q in ds_train.qrels_iter()
    ])

    q_test = pd.DataFrame([
        {
            "qid": q.query_id,
            "query": clean_query(q.text)
        }
        for q in ds_test.queries_iter()
    ])

    print(
        f"Train Queries: {len(q_train)} | "
        f"Snapshot3 Queries: {len(q_test)}"
    )

    # =====================================
    # INDEX
    # =====================================

    if not INDEX_DIR.exists():

        raise FileNotFoundError(
            "Index fehlt!"
        )

    index_path = str(
        INDEX_DIR.resolve()
    )

    print(
        "USING INDEX:",
        index_path
    )

    index = pt.IndexFactory.of(
        index_path
    )

    bm25 = pt.terrier.Retriever(
        index,
        wmodel="BM25",
        num_results=CAND_TOPK
    )

    # =====================================
    # RETRIEVAL
    # =====================================

    print("\n--- RETRIEVAL ---")

    cand_train = bm25.transform(
        q_train
    )

    cand_test = bm25.transform(
        q_test
    )

    # =====================================
    # FEATURE EXTRACTION
    # =====================================

    print(
        "\n--- FEATURE EXTRACTION ---"
    )

    doc_lens, doc_texts, doc_titles = (
        build_doc_caches([
            ds_docs_s1,
            ds_docs_s2,
            ds_docs_s3
        ])
    )

    get_yyyymm = build_meta_lookup(
        INDEX_DIR
    )

    (
        log_citation_map,
    ) = load_citation_features()

    cand_train = add_features(
        cand_train,
        q_train,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
        log_citation_map
    )

    cand_test = add_features(
        cand_test,
        q_test,
        doc_lens,
        doc_texts,
        doc_titles,
        get_yyyymm,
        log_citation_map
    )

    # Dense Features
    cand_train = add_dense_features_batched(
        cand_train,
        q_train,
        doc_texts
    )

    cand_test = add_dense_features_batched(
        cand_test,
        q_test,
        doc_texts
    )

    # =====================================
    # TRAIN LTR
    # =====================================

    print("\n--- TRAIN LTR ---")

    train_df = cand_train.merge(
        qrels,
        on=["qid", "docno"],
        how="left"
    )

    train_df["label"] = (
        train_df["label"]
        .fillna(0)
    )

    train_df = (
        train_df
        .sort_values(
            ["qid", "score"],
            ascending=[True, False]
        )
        .groupby("qid")
        .head(TRAIN_TOPK)
    )

    feature_cols = [
        "f_bm25",
        "f_qlen",
        "f_doclen",
        "f_recency",
        "f_overlap",
        "f_title_match",
        "f_dense",
        "f_log_citation_count",
    ]

    X = train_df[feature_cols]
    y = train_df["label"]

    group_sizes = (
        train_df
        .groupby("qid")
        .size()
        .tolist()
    )

    import lightgbm as lgb

    lgb_train = lgb.Dataset(
        X,
        label=y,
        group=group_sizes,
        free_raw_data=False
    )

    params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_eval_at": [10],
        "learning_rate": MODEL_LEARNING_RATE,
        "num_leaves": MODEL_NUM_LEAVES,
        "verbosity": -1,
    }

    model = lgb.train(
        params,
        lgb_train,
        num_boost_round=MODEL_NUM_TREES
    )

    # =====================================
    # SNAPSHOT 3 INFERENCE
    # =====================================

    print(
        "\n--- SNAPSHOT 3 INFERENCE ---"
    )

    # BM25
    bm25_test = cand_test.sort_values(
        ["qid", "score"],
        ascending=[True, False]
    )

    bm25_test["new_rank"] = (
        bm25_test
        .groupby("qid")
        .cumcount()
    )

    write_run_jsonl(
        bm25_test,
        RUN_BM25,
        "score"
    )

    # LTR
    ltr_test = cand_test.copy()

    ltr_test["ltr_score"] = (
        model.predict(
            ltr_test[feature_cols]
        )
    )

    ltr_test["bm25_norm"] = (
        ltr_test
        .groupby("qid")["score"]
        .transform(
            lambda x:
            (x - x.min())
            / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    ltr_test["ltr_norm"] = (
        ltr_test
        .groupby("qid")["ltr_score"]
        .transform(
            lambda x:
            (x - x.min())
            / (x.max() - x.min())
            if x.max() > x.min()
            else 0.0
        )
    )

    # Hybrid
    ltr_test["hybrid_score"] = (
        (1 - BEST_ALPHA)
        * ltr_test["bm25_norm"]
        + BEST_ALPHA
        * ltr_test["ltr_norm"]
    )

    ltr_test = ltr_test.sort_values(
        ["qid", "hybrid_score"],
        ascending=[True, False]
    )

    ltr_test["new_rank"] = (
        ltr_test
        .groupby("qid")
        .cumcount()
    )

    write_run_jsonl(
        ltr_test,
        RUN_HYBRID,
        "hybrid_score"
    )

    print("\nFertig!")

    print(
        f"BM25 Run: {RUN_BM25}"
    )

    print(
        f"Hybrid Run: {RUN_HYBRID}"
    )

    print("\nHinweis:")

    print(
        "Snapshot 3 besitzt "
        "keine öffentlichen Qrels."
    )

    print(
        "Daher wird keine "
        "nDCG@10 Evaluation berechnet."
    )


if __name__ == "__main__":
    main()